# Generated by Django 4.1.2 on 2023-05-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000)),
                ('Candidate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.candidate')),
                ('Company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.companies')),
            ],
        ),
    ]
