# Generated by Django 4.1.2 on 2022-10-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Candidates",
        ),
    ]
