# Generated by Django 4.1.2 on 2023-05-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('score', models.IntegerField()),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='Company.companies')),
                ('jobId', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='Company.job_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.questions')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalScore', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('candidateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='can', to='resume.candidate')),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compR', to='Company.companies')),
                ('jobId', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='joR', to='Company.job_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='ExamDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp', to='Company.companies')),
                ('jobId', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='jo', to='Company.job_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ansOp', to='exams.options')),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ansQn', to='exams.questions')),
            ],
        ),
    ]
