# Generated by Django 4.1.2 on 2022-11-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Company", "0001_initial"),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examduration",
            name="companyId",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comp",
                to="Company.companies",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examduration",
            name="jobId",
            field=models.ForeignKey(
                default=13,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jo",
                to="Company.job_profiles",
            ),
        ),
    ]
