# Generated by Django 4.1.2 on 2022-11-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_examresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
