# Generated by Django 4.1.2 on 2022-11-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_examduration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answers",
            name="optionId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ansOp",
                to="exams.options",
            ),
        ),
        migrations.AlterField(
            model_name="answers",
            name="questionId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ansQn",
                to="exams.questions",
            ),
        ),
    ]
