# Generated by Django 4.0.3 on 2022-10-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_name', models.CharField(max_length=100)),
                ('company_contact_no', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('companyuserid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pass1', models.CharField(default='', max_length=10)),
                ('pass2', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
