# Generated by Django 4.1.2 on 2023-04-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Company", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job_profiles",
            old_name="condi_tion",
            new_name="condition",
        ),
    ]
