# Generated by Django 4.1.2 on 2022-11-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_resume"),
        ("Company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="shortList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_id",
                        to="resume.candidate",
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_profile_id",
                        to="Company.job_profiles",
                    ),
                ),
            ],
        ),
    ]
