# Generated by Django 4.0.3 on 2022-10-31 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100)),
                ('job_info', models.TextField()),
                ('salary', models.CharField(max_length=100)),
                ('condi_tion', models.CharField(max_length=100)),
                ('no_of_vacancies', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.companies')),
            ],
        ),
    ]
