# Generated by Django 4.0.3 on 2022-10-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_job_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_profiles',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
