# Generated by Django 4.0.3 on 2022-10-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_remove_companies_id_alter_companies_companyuserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='pass1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='companies',
            name='pass2',
            field=models.CharField(default='', max_length=10),
        ),
    ]
