# Generated by Django 4.1.2 on 2022-11-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_resume"),
        ("Company", "0002_shortlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortlist",
            name="candidate_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candi_id",
                to="resume.candidate",
            ),
        ),
    ]
