# Generated by Django 4.1.2 on 2023-04-29 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Company", "0003_remove_job_profiles_condition"),
    ]

    operations = [
        migrations.CreateModel(
            name="industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("industry", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="job_profiles",
            name="postdate",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
