# Generated by Django 4.1.2 on 2022-11-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Company", "0003_alter_job_profiles_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job_profiles",
            name="salary",
            field=models.CharField(max_length=100),
        ),
    ]
