# Generated by Django 4.0.3 on 2022-11-06 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_alter_job_profiles_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.companies')),
                ('job_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.job_profiles')),
            ],
        ),
    ]
