# Generated by Django 4.1.2 on 2022-11-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="resumedata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("phno", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=70)),
                ("college", models.CharField(max_length=40)),
                ("cgpa", models.CharField(max_length=2)),
                ("comname", models.CharField(max_length=40)),
                ("brief", models.CharField(max_length=200)),
                ("start", models.CharField(max_length=4)),
                ("end", models.CharField(max_length=4)),
            ],
        ),
    ]
