# Generated by Django 4.1.2 on 2022-11-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prj_name", models.TextField(max_length=100)),
                ("prj_link", models.TextField(max_length=100)),
                ("prj_des", models.TextField(max_length=5000)),
                (
                    "candidateId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="resume.candidate",
                    ),
                ),
            ],
        ),
    ]
