# Generated by Django 4.1.2 on 2022-11-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_projects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work_experience",
            name="yr_of_exp",
        ),
    ]
