# Generated by Django 4.1.2 on 2022-11-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_remove_work_experience_yr_of_exp"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="platform",
            field=models.TextField(default="Edx", max_length=100),
        ),
    ]
